language: go

go:
 - 1.3.1
 - tip

matrix:
  fast_finish: true

env:
  global:
    - PATH=$HOME/gopath/bin:$PATH

install:
 - go get code.google.com/p/go.tools/cmd/vet
 - go get -t -v ./...
 - go install github.com/rjeczalik/ungocheck/cmd/ungocheck

script:
 - go tool vet -all .
 - go build ./...
 - go test -race -v ./...
 - ungocheck -race -v ./...

